#ifndef _APP_MAIN_PRO_H_
#define _APP_MAIN_PRO_H_

#define POWET_OFF_REVERSE_CHECK_TIME			T7S_10

#define APP_MONITOR_TIME				T180S_10
typedef enum
{
	OS_WORK_IDLE=0,
	OS_WAIT_ARM2_OK,
	OS_WAIT_APP_READY,
	OS_CHECK_REVERSE_ON,
	OS_WAIT_REVERSE_END,
	OS_WAIT_F_REVERSE_END,
	OS_CHECK_REVERSE_END,
	OS_POST_MESSAGE,
	OS_POST_SOURCE,
	OS_HARD_UNMUTE,
	OS_WORK_NORMAL
}OS_WORK_STATE;

typedef enum
{
	POWER_ON_TX_RESET_STATE=0,
	POWER_ON_TX_MCU_VERSION,
	POWER_ON_TX_CLOCK,
	POWER_ON_TX_VOLUME,
	POWER_ON_TX_DISC_STATE,
#if CANBOX_FUNC_MULTIPLE==1
	POWER_ON_TX_CAN_MULTIPLE,
#endif
#if MODEL==LINUX_N039_DZ
	POWER_ON_TX_HW_VERSION,
#endif		
	POWER_ON_TX_REVERSE_OFF,
	POWER_ON_TX_PARKING_STATE,
	POWER_ON_TX_ILLUME_STATE,
#if MODEL==LINUX_D068_55||MODEL==LINUX_D078_55||MODEL==LINUX_P058_55||MODEL==LINUX_6178_58||MODEL==LINUX_D065_55||MODEL==LINUX_D095_55
	POWER_ON_TX_AUX_STATE,
#endif
#if MODEL==LINUX_2289_31||MODEL==LINUX_2289_03
	POWER_ON_TX_SPEED_STATE,
#endif
	NUM_OF_POWER_ON_TX
}POWER_ON_TX_INDEX;

typedef enum
{
	APP_UPDATE_IDLE=0,
	APP_UPDATE_RESET_ON,
	APP_UPDATE_RESET_OFF,
	APP_UPDATE_START,
	APP_UPDATE_WAIT,
	APP_UPDATE_JUGEMENT,
	APP_UPDATE_ESCAPE,
	APP_UPDATE_END
}APP_UPDATE_STATE;

extern OS_WORK_STATE OS_WorkState;
extern APP_UPDATE_STATE AppUpdateState;
extern u16 APPMonitorTimer;
extern u16 AppReadyTimer;
extern u16 AppUpdateDetTimerB;
extern u8 AppUpdateFlagB;
extern u8 AppUpdateStatusB;
extern u8 AppUpdateFlagC;
extern u8 AppUpdateFlagD;
extern u8 AppResetCounter;
extern u8	Speed_Value;
extern u8 AppUpdating;

void APP_MainPro(void);
void OsWorkOn(void);
void OsWorkOff(void);
void AppUpdateStart(void);
#if PLATFORM_TYPE==SUNPLUS_8368U_PLATFORM||PLATFORM_TYPE==SUNPLUS_8268K_PLATFORM||PLATFORM_TYPE==SUNPLUS_8368U_MOTORCYCLE_PLATFORM||PLATFORM_TYPE==SUNPLUS_8368PU_PLATFORM
void AppUpdateGpioConfig(void);
#endif
#if PLATFORM_TYPE==SUNPLUS_8368PU_PLATFORM
void AppStartUpGpioConfig(void);
#endif
#if COMPATIBLE_WITH_NANDFLASH_EMMC_FUN==1
void Startup_Mode_Detect(void);
#endif
#endif

